name: Auto Convert Add Dotfiles

on:
  issues:
    types: [opened, edited, labeled]
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue number to process"
        required: true
        type: string

permissions:
  contents: write
  issues: read

jobs:
  auto-convert:
    runs-on: ubuntu-latest
    steps:
      - name: Get issue body (manual)
        if: github.event_name == 'workflow_dispatch'
        id: get_issue
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.payload.inputs.issue_number
            console.log('Using issue_number:', issue_number)
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: parseInt(issue_number)
            })
            core.setOutput('body', issue.data.body)
            core.setOutput('json', JSON.stringify(issue.data))
      - name: Check for auto-convert checkbox
        id: check_autoconvert
        run: |
          BODY="${{ github.event.issue.body }}"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            BODY="${{ steps.get_issue.outputs.body }}"
          fi
          if [[ "$BODY" = *"- [x] I want to automatically add it"* ]] || [[ "$BODY" = *"- [X] I want to automatically add it"* ]]; then
            echo "auto_convert=true" >> $GITHUB_OUTPUT
          else
            echo "auto_convert=false" >> $GITHUB_OUTPUT
          fi
      - name: Checkout repo
        if: steps.check_autoconvert.outputs.auto_convert == 'true'
        uses: actions/checkout@v4
      - name: Set up Node.js
        if: steps.check_autoconvert.outputs.auto_convert == 'true'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Run auto-add-dotfile script
        if: steps.check_autoconvert.outputs.auto_convert == 'true'
        env:
          ISSUE_JSON: ${{ github.event_name == 'workflow_dispatch' && steps.get_issue.outputs.json || toJson(github.event.issue) }}
        run: |
          echo "$ISSUE_JSON" | bun .github/scripts/auto-add-dotfile.mjs
      - name: Extract dotfiles info for PR
        if: steps.check_autoconvert.outputs.auto_convert == 'true'
        id: dotfiles_info
        env:
          ISSUE_JSON: ${{ github.event_name == 'workflow_dispatch' && steps.get_issue.outputs.json || toJson(github.event.issue) }}
        run: |
          ISSUE_DATA=$(echo "$ISSUE_JSON")
          USERNAME=$(echo "$ISSUE_DATA" | jq -r '.body' | grep -A1 "### Dotfiles URL" | tail -1 | sed 's|https://github.com/||' | cut -d'/' -f1)
          SECTION=$(echo "$ISSUE_DATA" | jq -r '.body' | grep -A1 "### DE or WM" | tail -1 | tr -d ' ')
          ISSUE_NUM=$(echo "$ISSUE_DATA" | jq -r '.number')
          echo "username=$USERNAME" >> $GITHUB_OUTPUT
          echo "section=$SECTION" >> $GITHUB_OUTPUT
          echo "issue_number=$ISSUE_NUM" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        if: steps.check_autoconvert.outputs.auto_convert == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat(readme): add ${{ steps.dotfiles_info.outputs.username }} dotfiles for ${{ steps.dotfiles_info.outputs.section }}"
          title: "add: ${{ steps.dotfiles_info.outputs.username }} dotfiles for ${{ steps.dotfiles_info.outputs.section }}"
          body: |
            Auto-generated PR from issue #${{ steps.dotfiles_info.outputs.issue_number }}

            Added ${{ steps.dotfiles_info.outputs.username }}'s dotfiles to the ${{ steps.dotfiles_info.outputs.section }} section.
          branch: "auto/add-dotfile-${{ steps.dotfiles_info.outputs.issue_number }}"
          delete-branch: true
