name: Auto Convert Add Dotfiles

on:
  issues:
    types: [opened, edited, labeled]
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue number to process"
        required: true
        type: string

jobs:
  auto-convert:
    runs-on: ubuntu-latest
    steps:
      - name: Get issue body (manual)
        if: github.event_name == 'workflow_dispatch'
        id: get_issue
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.payload.inputs.issue_number
            console.log('Using issue_number:', issue_number)
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: parseInt(issue_number)
            })
            core.setOutput('body', issue.data.body)
            core.setOutput('json', JSON.stringify(issue.data))
      - name: Check for auto-convert checkbox
        id: check_autoconvert
        run: |
          BODY="${{ github.event.issue.body }}"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            BODY="${{ steps.get_issue.outputs.body }}"
          fi
          if [[ "$BODY" = *"- [x] I want to automatically add it"* ]] || [[ "$BODY" = *"- [X] I want to automatically add it"* ]]; then
            echo "auto_convert=true" >> $GITHUB_OUTPUT
          else
            echo "auto_convert=false" >> $GITHUB_OUTPUT
          fi
      - name: Checkout repo
        if: steps.check_autoconvert.outputs.auto_convert == 'true'
        uses: actions/checkout@v4
      - name: Set up Node.js
        if: steps.check_autoconvert.outputs.auto_convert == 'true'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Run auto-add-dotfile script (workflow_dispatch)
        if: steps.check_autoconvert.outputs.auto_convert == 'true' && github.event_name == 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_JSON: ${{ steps.get_issue.outputs.json }}
        run: |
          echo "$ISSUE_JSON" | bun .github/scripts/auto-add-dotfile.mjs
      - name: Run auto-add-dotfile script (issues)
        if: steps.check_autoconvert.outputs.auto_convert == 'true' && github.event_name != 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_JSON: ${{ toJson(github.event.issue) }}
        run: |
          echo "$ISSUE_JSON" | bun .github/scripts/auto-add-dotfile.mjs
