name: Auto Convert Add Dotfiles

on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      issue_number:
        description: "Issue number to process"
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  auto-convert:
    runs-on: ubuntu-latest
    steps:
      - name: Get issue body (manual)
        if: github.event_name == 'workflow_dispatch'
        id: get_issue
        uses: actions/github-script@v7
        with:
          script: |
            const issue_number = context.payload.inputs.issue_number
            console.log('Using issue_number:', issue_number)
            const issue = await github.rest.issues.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: parseInt(issue_number)
            })
            core.setOutput('body', issue.data.body)
            core.setOutput('json', JSON.stringify(issue.data))
      - name: Check for auto-convert checkbox
        id: check_autoconvert
        run: |
          BODY="${{ github.event.issue.body }}"
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            BODY="${{ steps.get_issue.outputs.body }}"
          fi
          if [[ "$BODY" = *"- [x] I want to automatically add it"* ]] || [[ "$BODY" = *"- [X] I want to automatically add it"* ]]; then
            echo "auto_convert=true" >> $GITHUB_OUTPUT
          else
            echo "auto_convert=false" >> $GITHUB_OUTPUT
          fi
      - name: Checkout repo
        if: steps.check_autoconvert.outputs.auto_convert == 'true'
        uses: actions/checkout@v4
      - name: Set up Node.js
        if: steps.check_autoconvert.outputs.auto_convert == 'true'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Run auto-add-dotfile script
        if: steps.check_autoconvert.outputs.auto_convert == 'true'
        env:
          ISSUE_JSON: ${{ github.event_name == 'workflow_dispatch' && steps.get_issue.outputs.json || toJson(github.event.issue) }}
        run: |
          echo "$ISSUE_JSON" | bun .github/scripts/auto-add-dotfile.mjs
      - name: Extract dotfiles info for PR
        if: steps.check_autoconvert.outputs.auto_convert == 'true'
        id: dotfiles_info
        env:
          ISSUE_JSON: ${{ github.event_name == 'workflow_dispatch' && steps.get_issue.outputs.json || toJson(github.event.issue) }}
        run: |
          ISSUE_DATA=$(echo "$ISSUE_JSON")
          BODY=$(echo "$ISSUE_DATA" | jq -r '.body')

          # Extract username from dotfiles URL using more robust parsing
          DOTFILES_URL=$(echo "$BODY" | sed -n '/### Dotfiles URL/,/### /p' | grep "https://github.com/" | head -1 | xargs)
          USERNAME=$(echo "$DOTFILES_URL" | sed 's|https://github.com/||' | cut -d'/' -f1)

          # Extract section from DE or WM field
          SECTION=$(echo "$BODY" | sed -n '/### DE or WM/,/### /p' | grep -v "### " | head -1 | xargs)

          # Extract issue number
          ISSUE_NUM=$(echo "$ISSUE_DATA" | jq -r '.number')

          echo "DEBUG: USERNAME='$USERNAME'"
          echo "DEBUG: SECTION='$SECTION'"
          echo "DEBUG: ISSUE_NUM='$ISSUE_NUM'"

          echo "username=$USERNAME" >> $GITHUB_OUTPUT
          echo "section=$SECTION" >> $GITHUB_OUTPUT
          echo "issue_number=$ISSUE_NUM" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        if: steps.check_autoconvert.outputs.auto_convert == 'true'
        id: create_pr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "feat(readme): add ${{ steps.dotfiles_info.outputs.username }} dotfiles for ${{ steps.dotfiles_info.outputs.section }}"
          title: "add: ${{ steps.dotfiles_info.outputs.username }} dotfiles for ${{ steps.dotfiles_info.outputs.section }}"
          body: |
            Auto-generated PR from issue #${{ steps.dotfiles_info.outputs.issue_number }}

            Added ${{ steps.dotfiles_info.outputs.username }}'s dotfiles to the ${{ steps.dotfiles_info.outputs.section }} section.
          branch: "auto/add-dotfile-${{ steps.dotfiles_info.outputs.issue_number }}"
          delete-branch: true
          assignees: 0PandaDEV
      - name: Comment on issue
        if: steps.check_autoconvert.outputs.auto_convert == 'true' && steps.create_pr.outputs.pull-request-number
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = ${{ steps.dotfiles_info.outputs.issue_number }};
            const prNumber = ${{ steps.create_pr.outputs.pull-request-number }};
            const username = '${{ steps.dotfiles_info.outputs.username }}';
            const section = '${{ steps.dotfiles_info.outputs.section }}';

            // Comment on the issue with PR link
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issueNumber,
              body: `🎉 **Automation Success!**

            Your dotfiles have been automatically processed and added to the list!

            **Details:**
            - **Username:** ${username}
            - **Section:** ${section}
            - **Pull Request:** #${prNumber}

            The pull request has been created and your dotfiles will be visible once it's merged. Thank you for contributing to awesome-unixporn! ✨
            });
